<?php

namespace Omnipay\PaymentgateRu\Message;

use Omnipay\Common\Message\RedirectResponseInterface;

class AuthorizeResponse extends AbstractCurlResponse implements RedirectResponseInterface
{
    /**
     * Does the response require a redirect?
     * Success response is a redirect
     *
     * @return boolean
     */
    public function isRedirect()
    {
        return $this->isSuccessful();
    }

    /**
     * Gets the redirect target url.
     *
     * @return string
     */
    public function getRedirectUrl()
    {
        return $this->data['formUrl'];
    }

    /**
     * Get the required redirect method (either GET or POST).
     *
     * @return string
     */
    public function getRedirectMethod()
    {
        return 'GET';
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->isSuccessful() ? $this->data['orderId'] : null;
    }

    /**
     * Gets the redirect form data array, if the redirect method is POST.
     *
     * @return array
     */
    public function getRedirectData()
    {
        return array();
    }
}
